name: NetherAccessController
version: '${project.version}'
main: dansplugins.netheraccesscontroller.NetherAccessController
api-version: 1.13
author: DanTheTechMan

commands:
  nac:

permissions:
  nac.help:
    default: op
  nac.list:
    default: op
  nac.allow:
    default: op
  nac.deny:
    default: op
  nac.config:
    default: op