name: NetherAccessController
version: 0.6
main: dansplugins.netheraccesscontroller.NetherAccessController
api-version: 1.13
author: DanTheTechMan

commands:
  nac:

permissions:
  wac.help:
    default: op
  wac.list:
    default: op
  wac.allow:
    default: op
  wac.deny:
    default: op
  wac.config:
    default: op